### ISSUE TITLE
Hueco en pared

### ISSUE THREAD

**Issue by IAymat** [Proyectos1-FDI-UCM/c2022-Grupo02#4]
### Descripción

Falla la colisión con la pared y permite atravesarla, cayendo al vacío.

### Pasos 

En la prueba de movimiento, tras coger el powerup de doble salto y caer atravesando los "bloques trampa", poco antes de llegar a la salida:

1. No dirigirse a la derecha como parece natural
2. Caminar hacia la izquierda hasta la pared y continuar
3. Se puede comprobar también saltando hacia la pared

### Capturas de pantalla
![Captura de pantalla 2022-04-27 184509](https://user-images.githubusercontent.com/99961714/165584594-32d0ef4a-1eaf-47c7-a45a-8d289178013f.jpg)
![Captura de pantalla 2022-04-27 184659](https://user-images.githubusercontent.com/99961714/165584608-3ad9a71d-c94d-4554-ac18-cca890c83a72.jpg)

**Comment by neutronbomb23** [comment]
Error solucionado, gracias!
